### ISSUE TITLE
Can build project because of fusioncharts

### ISSUE THREAD

**Issue by ShininingLancer** [fusioncharts/react-fusioncharts-component#22]
I am developing react project created by create-react-app. I don't use webpack. just project created by create-react-app.

Now I want to build using "npm run build", but i can't because of the error following:

Failed to minify the code from this file:

        ./node_modules/fusioncharts/_internal/lib/lib.js:1:9788

**Comment by zeeeengxin** [comment]
Hi, I ran into exactly the same problem! It took me a long time to finally figure out a way to build my project!

Try the following steps:
1. `npm run eject` so that we can change the config options by ourselves.

> Note: this is a one-way operation. Once you eject, you can’t go back!
> If you aren’t satisfied with the build tool and configuration choices, you can eject at any time. This command will remove the single build dependency from your project.

2. Remove all import of fusioncharts from your source file e.g. remove everything like `import Column2D from 'fusioncharts/xxx/xxx';`
Keep `import ReactFC from 'react-fusioncharts';` don't remove this. 

3. In `public/index.html` file, import react, react-dom, bable (dependencies of fusionchars) and fusioncharts, react-fusioncharts using CDN with `<script>` tag. So that we don't need to install these packages with npm, don't need to build them into the `build` folder, and therefore no need to minify it and won't cause the problem.

4. In `config/webpack.config.prod.js`, add code below so that when build with webpack, it will ignore fusioncharts:
```
externals: {
    "fusioncharts/core": "FusionCharts",
    'react-fusioncharts': "ReactFC",
  },
```

It works for me. Hope it can help you as well.

**Comment by alangrn** [comment]
Does this still exist? I am about to try compile my code. How would one do this without using a CDN?

**Comment by Cosmo439** [comment]
Ejecting to solve this problem is a bad solution in my case. I don't want to have to manage all of the configuration files.

Yes, this is still a problem. The code published to npm needs to be pre-compiled.

> Create React App can consume both CommonJS and ES modules. For Node.js compatibility, it is recommended that the main entry point is CommonJS. However, they can optionally provide an ES module entry point with the module field in package.json. Note that even if a library provides an ES Modules version, it should still precompile other ES6 features to ES5 if it intends to support older browsers.

**Comment by ashok1994** [comment]
We recommend to follow the updated documentation , @ShininingLancer  , which is using es5 version of fusioncharts , docs in readme https://github.com/fusioncharts/react-fusioncharts-component.

Closing for now

**Comment by Cosmo439** [comment]
The documentation in the readme does not explain how to install the ES5 version of fusioncharts. Can you please clarify?

**Comment by ashok1994** [comment]
@Cosmo439  
```

import FusionCharts from 'fusioncharts'; // ES5 fusioncharts
import Charts from 'fusioncharts/fusioncharts.charts';
import ReactFC from 'react-fusioncharts';
ReactFC.fcRoot(FusionCharts, Charts);
```
Currently there is endpoint for ES6 version 
which is 
`
import FusionCharts from 'fusioncharts/core';
`
But currently due to the limitation of react 's build system  , we are discouraging the usage of this

**Comment by Cosmo439** [comment]
Thank you for pointing that out, I was having trouble because I was using a SparkLine, which needed 'fusioncharts/fusioncharts.widget' instead of 'fusioncharts/fusioncharts.charts'.

Do you know of any way to suppress the warning: `A deprecated way of resolving FusionCharts as a dependency is detected. Please use FusionCharts.addDep instead. For more information, please visit https://www.fusioncharts.com/dev/getting-started/plain-javascript/install-using-plain-javascript#install-fusioncharts-via-npm-5`?

This is not a huge deal, but it annoys me.

**Comment by ashok1994** [comment]
@Cosmo439  , that warning is removed in 3.13.1-sr.2 , current latest version , update your fusioncharts if you are in a older version

**Comment by Cosmo439** [comment]
Thank you again.
