### ISSUE TITLE
Chart Type World, label unexpected border displayed.

### ISSUE THREAD

**Issue by jeetendra-choudhary** [fusioncharts/react-fusioncharts-component#44]
The world map label shows an unexpected rounded border. The html element which gets generated at runtime is as below -

`<rect x="629.40625" y="257" width="62.828125" height="31.15625" ry="10" rx="10" fill="none" stroke="#666666" stroke-opacity="0.9" stroke-width="1" shape-rendering="crispEdges" stroke-dasharray="none" style="shape-rendering: crispedges; cursor: default;" opacity="1"></rect>`

This is how it looks -

![image](https://user-images.githubusercontent.com/19362419/52035745-1e279500-2551-11e9-9675-4cabd9221504.png)

**Comment by siawo** [comment]
@jeetendra-choudhary can you please share a scale down version of your implementation?

**Comment by AyanBhadury** [comment]
@jeetendra-choudhary We tried replicating the issue at our end but we are unable to replicate it. The chart seems to be working fine at our end, here is a link to the working demo: https://codesandbox.io/s/overlapped-demo-react-forked-0bruv?file=/src/App.js.
Could you please try with the demo above and let us know if you still face any issues? If you face any issue kindly fork the demo and send us so that we can further investigate it.
